import type { Config } from 'tailwindcss';

const config: Config = {
  darkMode: ['class'],
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    container: { center: true, padding: '2rem', screens: { '2xl': '1400px' } },
    extend: {
      colors: {
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        primary: { DEFAULT: 'hsl(var(--primary))', foreground: 'hsl(var(--primary-foreground))' },
        secondary: { DEFAULT: 'hsl(var(--secondary))', foreground: 'hsl(var(--secondary-foreground))' },
        destructive: { DEFAULT: 'hsl(var(--destructive))', foreground: 'hsl(var(--destructive-foreground))' },
        muted: { DEFAULT: 'hsl(var(--muted))', foreground: 'hsl(var(--muted-foreground))' },
        accent: { DEFAULT: 'hsl(var(--accent))', foreground: 'hsl(var(--accent-foreground))' },
        popover: { DEFAULT: 'hsl(var(--popover))', foreground: 'hsl(var(--popover-foreground))' },
        card: { DEFAULT: 'hsl(var(--card))', foreground: 'hsl(var(--card-foreground))' },
        // Custom Overrides mapped to CSS variables for Theme Support
        slate: {
          50: 'var(--theme-slate-50)',
          100: 'var(--theme-slate-100)',
          200: 'var(--theme-slate-200)',
          300: 'var(--theme-slate-300)',
          400: 'var(--theme-slate-400)',
          500: 'var(--theme-slate-500)',
          600: 'var(--theme-slate-600)',
          700: 'var(--theme-slate-700)',
          800: 'var(--theme-slate-800)',
          900: 'var(--theme-slate-900)',
          950: 'var(--theme-slate-950)',
        },
        blue: {
          50: 'var(--theme-blue-50)',
          100: 'var(--theme-blue-100)',
          200: 'var(--theme-blue-200)',
          300: 'var(--theme-blue-300)',
          400: 'var(--theme-blue-400)',
          500: 'var(--theme-blue-500)',
          600: 'var(--theme-blue-600)',
          700: 'var(--theme-blue-700)',
          800: 'var(--theme-blue-800)',
          900: 'var(--theme-blue-900)',
          950: 'var(--theme-blue-950)',
        },
        emerald: {
          50: 'var(--theme-emerald-50)',
          100: 'var(--theme-emerald-100)',
          200: 'var(--theme-emerald-200)',
          300: 'var(--theme-emerald-300)',
          400: 'var(--theme-emerald-400)',
          500: 'var(--theme-emerald-500)',
          600: 'var(--theme-emerald-600)',
          700: 'var(--theme-emerald-700)',
          800: 'var(--theme-emerald-800)',
          900: 'var(--theme-emerald-900)',
          950: 'var(--theme-emerald-950)',
        },
        rose: {
          50: 'var(--theme-rose-50)',
          100: 'var(--theme-rose-100)',
          200: 'var(--theme-rose-200)',
          300: 'var(--theme-rose-300)',
          400: 'var(--theme-rose-400)',
          500: 'var(--theme-rose-500)',
          600: 'var(--theme-rose-600)',
          700: 'var(--theme-rose-700)',
          800: 'var(--theme-rose-800)',
          900: 'var(--theme-rose-900)',
          950: 'var(--theme-rose-950)',
        },
        amber: {
          50: 'var(--theme-amber-50)',
          100: 'var(--theme-amber-100)',
          200: 'var(--theme-amber-200)',
          300: 'var(--theme-amber-300)',
          400: 'var(--theme-amber-400)',
          500: 'var(--theme-amber-500)',
          600: 'var(--theme-amber-600)',
          700: 'var(--theme-amber-700)',
          800: 'var(--theme-amber-800)',
          900: 'var(--theme-amber-900)',
          950: 'var(--theme-amber-950)',
        },
        // Priority colors
        critical: 'var(--theme-rose-500)',
        high: 'var(--theme-emerald-500)',
        medium: 'var(--theme-amber-500)',
        low: 'var(--theme-slate-200)',
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
      keyframes: {
        'accordion-down': { from: { height: '0' }, to: { height: 'var(--radix-accordion-content-height)' } },
        'accordion-up': { from: { height: 'var(--radix-accordion-content-height)' }, to: { height: '0' } },
        'slide-in-from-right': { '0%': { transform: 'translateX(100%)' }, '100%': { transform: 'translateX(0)' } },
        'notification-pulse': { '0%,100%': { opacity: '1' }, '50%': { opacity: '0.5' } },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
        'slide-in': 'slide-in-from-right 0.3s ease-out',
        'notification-pulse': 'notification-pulse 1s ease-in-out 3',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
};

export default config;
