"""Add TenantTifluxConfig table

Revision ID: a345d2f8b4d3
Revises: c1075ed1f5df
Create Date: 2026-05-21 19:05:21.795198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a345d2f8b4d3'
down_revision: Union[str, Sequence[str], None] = 'c1075ed1f5df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant_tiflux_config',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('tiflux_api_key', sa.Text(), nullable=False),
    sa.Column('tiflux_client_id', sa.String(length=50), nullable=False),
    sa.Column('tiflux_desk_id', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tenant_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tenant_tiflux_config')
    # ### end Alembic commands ###
